title: Lidar NRW
email: jacob.mendt@pikobytes.de
description: >- # this means to ignore newlines until "baseurl:"
 Das ist eine DEMO, welche Lidar-Daten von NRW nutzt und diese mittels mapboxgl und deckgl darstellt.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
github_username:  jacmendt

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
